# Generated by Django 4.2.5 on 2023-09-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbooking', '0003_booking_trip_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='price',
            new_name='adult_price',
        ),
        migrations.AddField(
            model_name='flight',
            name='Child_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
