# Generated by Django 4.2.5 on 2023-09-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbooking', '0004_rename_price_flight_adult_price_flight_child_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='Child_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='adult_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
