# Generated by Django 4.2.5 on 2023-09-30 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbooking', '0006_rename_child_price_flight_child_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='booking',
            name='departure_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='flight',
            name='return_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
