# Generated by Django 4.2.5 on 2023-09-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbooking', '0008_booking_total_amount_flight_trip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='select_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('first_class', 'First Class')], default='economy', max_length=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='select_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('first_class', 'First Class')], default='economy', max_length=20),
        ),
    ]
