# Generated by Django 4.2.5 on 2023-10-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0002_remove_amenity_hotel_remove_hotelimage_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='hotels', to='hotelbooking.hotelimage'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(null=True, upload_to='hotel_images/'),
        ),
    ]
