# Generated by Django 4.2.5 on 2023-10-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0003_alter_hotel_images_alter_hotelimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
