# Generated by Django 4.2.5 on 2023-10-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0004_carmake_remove_car_make_carmodel_alter_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='makes',
            field=models.ManyToManyField(related_name='cars', to='carbooking.carmake'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='carbooking.carmodel'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='carbooking.carmake'),
        ),
    ]
