# Generated by Django 4.2.5 on 2023-10-04 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0005_car_makes_alter_car_model_alter_carmodel_make'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='makes',
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.ForeignKey(default='Toyota', on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='carbooking.carmake'),
        ),
    ]
